repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        name: "Run ruff linter and import sorter"
        args: [ "--fix", "--exit-non-zero-on-fix" ]
      - id: ruff-format
        name: "Run ruff formatter"